[package]
name = "sage-core"
version = "0.15.0-beta.1.decoyfree-prealpha.1"
authors = [
    "Michael Lazear <michaellazear92@gmail.com>",
    "jltovar <jltovar>",
]
edition = "2021"
rust-version = "1.85"
description = "A very fast proteomics database search tool, now decoy-free"
readme = "README.md"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = { version = "5.4.0", features = ["rayon"] }
fnv = "1.0"
itertools = "0.10"
log = "0.4.0"
rayon = "1.5"
regex = "1.6"
serde = { version="1.0", features = ["derive"] }
argmin = "0.10.0"
argmin-math = { version = "0.4.0", features = ["nalgebra_latest"] }
nalgebra = "0.32"
statrs = "0.18.0"
adjustp = "0.1.6"
rand = "0.8"

[dev-dependencies]
criterion = "0.4"
quickcheck = "1"
quickcheck_macros = "1"

[features]
bench = []
decoy_free_debug = []

[[bench]]
name = "decoy_free_perf"
harness = false
required-features = ["bench"]
